language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0


matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0

    - python: 3.4
      env: DJANGO=2.0

    - python: 3.6
      env: DJANGO=1.10


install:
  - pip install tox codecov

script:
  - tox -e "d${DJANGO//.}-py${TRAVIS_PYTHON_VERSION//.}" -- py.test tests/ --create-db

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
