language: python
sudo: false
python:
    - 3.5
env:
  - TOXENV=py27-d18
  - TOXENV=py27-d19
  - TOXENV=py27-d110
  - TOXENV=py27-d111

  - TOXENV=py35-d18
  - TOXENV=py35-d19
  - TOXENV=py35-d110
  - TOXENV=py35-d111


install:
  - pip install tox "coverage<4.0" python-coveralls>=2.5 coveralls>=0.5 codecov

script:
  - tox -re $TOXENV -- py.test tests/ --create-db -v --capture=no --cov=strategy_field --cov-report=xml --cov-config=tests/.coveragerc

before_success:
  - coverage erase

after_success:
  - coverage combine
  - coveralls
  - codecov
